Client first version
eampleev23/gophkeeper pull request #3
Opened 2024-10-15 10:49 UTC by eampleev23

2024-10-21 15:26 UTC, nburunova commented
нужно добавить юнит-тесты, покрытие кода не менее 80%

2024-10-21 16:32 UTC, nburunova requested changes

2024-10-21 16:32 UTC, nburunova commented on cmd/client/create_new_login_password_item.go
> +	request, err := http.NewRequest(http.MethodPost, "http://localhost:8080/api/user/add-login-password", bytes.NewBuffer(loginPassNewItemRequestBytes))
адрес сервиса и путь лучше не хардкодить, а иметь возможность задать конфигом, так как адрес и url могут поменяться (переехать на другой сервер, может обновиться версия и url будет типа /api/v2/user...). В случае хардкода нужно будет пересобирать приложение, а в случае, если эти значения будут задаваться через конфиг, то можно будет просто перезапустить приложения с новым конфигом

2024-10-21 16:32 UTC, nburunova commented on cmd/client/create_new_login_password_item.go
> +		fmt.Println("Ошибка, попробуйте обновить версию клиента")
тут надо return сделать, чтобы прервать выполнение функции?

2024-10-21 16:32 UTC, nburunova commented on cmd/client/create_new_login_password_item.go
> +		fmt.Println("Ошибка получения ответа от сервера, попробуйте обновить версию клиента")
return , и ниже по коду тоже return-ы нужны

2024-10-21 16:32 UTC, nburunova commented on cmd/client/login.go
> +					return []byte("e4853f5c4810101e88f1898db21c15d3"), nil
хардкод не приветствуется. Кстати, что это за значение? Дефолтный токен?

2024-10-21 16:32 UTC, nburunova commented on cmd/client/login.go
> +					fmt.Println("Ошибка авторизации, обратитесь к администратору")
кажется return нужно?

2024-10-21 16:32 UTC, nburunova commented on cmd/client/login.go
> +		for _, v := range response.Cookies() {
я бы вынесла код, который вызывается в случае response != nil в отдельную функцию. Сейчас login функция слишком сложная. Будет читабельнее, если разбить ее на несколько ф-ций

2024-10-21 16:32 UTC, nburunova commented on cmd/client/show_data_item.go
> +	//var loginPassRequestStr = `{"id": "`
закоментированные строчки кода попали в ПР, надо удалить неиспользуемый код

2024-10-21 16:32 UTC, nburunova commented on cmd/client/show_data_item.go
> +	request.Header.Set("Content-Type", "application/json; charset=UTF-8")
код создания запроса,выполнение запроса и пасинга ответа дублируется в нескольких фукнциях. Советую вынести в одну фукнцию типа request(...) и вызывать во всех меню , только с сооветствующим набором аргументов. В целом нужно избегать дублирующегося кода и пытаться выделить его в фукнкцию, которую можно переиспользовать

2024-10-21 16:32 UTC, nburunova commented on cmd/client/show_data_item.go
> +		fmt.Printf("error: %v\n", err)
может вместо fmt завести какой-то logger?

2024-10-21 16:32 UTC, nburunova commented on internal/cnf/cnf.go
> +package cnf
давай тут пакет и файл назовем config? я не сразу поняла, что значит cnf, пока файл не открыла :)

2024-10-21 16:32 UTC, nburunova commented on internal/handlers/add_login_password.go
> +	fmt.Println("ownerID=", ownerID)
почему в fmt ,а не в logger?

2024-10-21 16:32 UTC, nburunova commented on internal/handlers/get_data_items.go
> +	if !isAuth {
эти проверки на авторизацию можно перенести в middleware по авторизации?

2024-10-21 16:32 UTC, nburunova commented on internal/myauth/myauth_ref.go
> +		au.l.ZL.Info("Failed in case to get ownerId from token ", zap.Error(err))
return err?

2024-10-21 16:32 UTC, nburunova commented on internal/store/db_store_create.go
> +	cost := 14
вынести в константы и дать более говорящее имя

2024-10-21 16:32 UTC, nburunova commented on internal/store/db_store_create.go
> +	key := []byte("TuUdlQmYyD1DTaiGVV31ipyWnbKa0jUD")
точно ли ключ должен быть захардкожен?

2024-10-21 16:32 UTC, nburunova commented on internal/store/db_store_create.go
> +	encryptedLoginStr := byteToString(encryptedLogin)
в БД постгреса есть бинарные типы данных.

2024-10-21 16:32 UTC, nburunova commented on internal/store/db_store_create.go
> +func byteToString(b []byte) string {
можно просто string([]byte)

2024-10-21 16:32 UTC, nburunova commented on internal/store/store.go
> +type Store interface {
интерфейс обычно объявляется там, где он используется, перенеси туда, где используется

2024-10-22 09:54 UTC, eampleev23 commented on cmd/client/login.go
> +					return []byte("e4853f5c4810101e88f1898db21c15d3"), nil
Это ключ для расшифровки токены из куки (получение id и логина пользователя) - используется и на сервере и на клиенте.. Упал в конфигурацию клиента.

2024-10-22 11:20 UTC, eampleev23 commented on cmd/client/show_data_item.go
> +		fmt.Printf("error: %v\n", err)
Я вообще до этого клиент не писал, у меня был сокращатель ссылок.. Но кажется что в консольном клиенте нет смысла в каком-то логгере, мы выводим ошибку пользователю в консоль, для этого и есть fmt.. Или я не прав?

2024-10-22 12:51 UTC, eampleev23 commented on internal/handlers/get_data_items.go
> +	if !isAuth {
Теоретически да, я когда-то это делал в первом дипломе или в сокращаете ссылок, но не помню почему в итоге вернулся опять к проверке в хэндлере - кажется так код выглядит понятнее и прозрачнее (там еще специфика с chi на сколько я помню и с путями) Если это принципиальный момент, то разберусь, но мне так точно понятнее, чем когда эта логика спрятана в миддлваре и работает не для всех хэндлеров одинаково.

2024-10-22 12:55 UTC, eampleev23 commented on internal/handlers/get_data_items.go
> +	if !isAuth {
вот нашел обсуждение на эту тему с другим ментором: https://github.com/eampleev23/diploma/pull/10#discussion_r1599352384

2024-10-22 13:18 UTC, eampleev23 commented on internal/store/db_store_create.go
> +	key := []byte("TuUdlQmYyD1DTaiGVV31ipyWnbKa0jUD")
Вопрос хороший.. Тоже об этом думал. Сейчас вынес его в конфигурацию со значением по умолчанию.. Но надо понимать что он симметричный и на клиенте при расшифровке должен использоваться тот же что и на сервере.

2024-10-22 13:19 UTC, eampleev23 commented on internal/store/db_store_create.go
> +	key := []byte("TuUdlQmYyD1DTaiGVV31ipyWnbKa0jUD")
Здесь тоже вопрос сразу возник возможно ли бинарник клиента взломать и вытащить оттуда этот ключ если он там захардкожен был?

2024-10-22 13:22 UTC, eampleev23 commented on internal/store/db_store_create.go
> +func byteToString(b []byte) string {
Я по не знанию переводил байты в строки и разделял их "!" - вообще так можно дополнительно шифровать данные и таким образом повысить безопасность, но скорее всего перепишу на байты

2024-10-22 13:26 UTC, eampleev23 commented on internal/store/store.go
> +type Store interface {
<img width="1523" alt="Снимок экрана 2024-10-22 в 16 24 17" src="https://github.com/user-attachments/assets/27878115-1fc1-4257-8ddc-fe6637459f1f">
он у меня используется в 6 файлах.. в какой из них перенести не очень понял..

2024-10-23 04:59 UTC, eampleev23 commented on internal/store/db_store_create.go
> +	encryptedLoginStr := byteToString(encryptedLogin)
Сделал хранение логина в бинарном типе в бд.. Остальные данные пока оставил в строках со своей функцией расшифровки и перевода в байты и назад

2024-10-23 05:06 UTC, eampleev23 commented on internal/store/db_store_create.go
> +func byteToString(b []byte) string {
нельзя т.к. там есть определенный алгоритм расшифровки строки в байты. переименовал функцию в packBytesToString чтобы понятнее было

2024-11-05 01:03 UTC, merged