Final version
eampleev23/gophkeeper pull request #8
Opened 2024-10-22 03:51 UTC by eampleev23

2024-11-01 17:09 UTC, nburunova requested changes

2024-11-01 17:09 UTC, nburunova commented on cmd/client/main.go
> +		//register(client, cmd, qh)
убрать закомментированный код

2024-11-01 17:09 UTC, nburunova commented on internal/client/login_client.go
> +		fmt.Println("Ошибка, попробуйте обновить версию клиента")
кажется забыл return

2024-11-01 17:09 UTC, nburunova commented on db/migrations/00018_files1.down.sql
пустые файлы?

2024-11-01 17:09 UTC, nburunova commented on cmd/server/server
бинари не складывают в репозиторий с кодом.
сборки обычно в других системах хранятся, не в репозитории

2024-11-01 17:09 UTC, nburunova commented on cmd/client/client
бинари не складываем в репозиторий с кодом. Тут только код должен быть 
Сборки обычно с других системах хранятся

2024-11-01 17:09 UTC, nburunova commented on internal/client/config.go
> +		fmt.Println("Ошибка клиента, попробуйте обновить версию..")
return

2024-11-01 17:09 UTC, nburunova commented on internal/client/config.go
> +	flag.StringVar(&clientApp.SecretKey, "s", "e4853f5c4810101e88f1898db21c15d3", "server's secret key for authorization")
валидные секретные ключи нельзя хранить в коде. Тут лучше не использовать какой-то дефолтный

2024-11-01 17:09 UTC, nburunova commented on internal/client/create_new_text_data.go
> +	if response.StatusCode != http.StatusBadRequest {
проверка 400, 500 и 403 кодов повторяется во всех хендлерах, лучше вынести в отдельную функцию

2024-11-01 17:09 UTC, nburunova commented on cmd/client/main.go
> +		app.Login(nil)
вроде Login возвращает ошибку, нужно проверять ее, нельзя оставлять ошибки без проверки

2024-11-01 17:09 UTC, nburunova commented on cmd/client/main.go
> +		app.Register()
обрабатывать ошибку от register

2024-11-01 17:09 UTC, nburunova commented on internal/handlers/add_file.go
> +	// Maximum upload of 10 MB files
это требование где-то в меню отображено?

2024-11-01 17:09 UTC, nburunova commented on internal/handlers/add_file.go
> +		fmt.Println(err)
w.WriteHeader(http.StatusInternalServerError) или http.Error(w, err.Error(), http.StatusInternalServerError)?

2024-11-01 17:09 UTC, nburunova commented on internal/store/db_store_create.go
> +	var result string
а просто string(b) не срабает? есть какие-то ньюансы?

2024-11-04 12:21 UTC, eampleev23 commented on internal/client/config.go
> +	flag.StringVar(&clientApp.SecretKey, "s", "e4853f5c4810101e88f1898db21c15d3", "server's secret key for authorization")
да, его можно задать при сборке, но нужно использовать именно один и тот же

2024-11-04 12:47 UTC, eampleev23 commented on internal/store/db_store_create.go
> +	var result string
да, храню в зашифрованных строках байты, своя функция расшифровки..

2024-11-04 13:59 UTC, nburunova requested changes

2024-11-04 13:59 UTC, nburunova commented on internal/client/config.go
> +	flag.StringVar(&clientApp.SecretKey, "s", "e4853f5c4810101e88f1898db21c15d3", "server's secret key for authorization")
тогда может из файла вычитывать? в самом коде нельзя хранить ключи. В каких-то других местах - файл ключа например

2024-11-04 16:56 UTC, nburunova approved these changes

2024-11-05 01:03 UTC, merged